/* ============================================================
   Per-vertical demo datasets.
   Shape mirrors what the on-machine runtime pushes (state.py),
   plus presentation fields. Ordered to LEAD with the highest-ROI
   workflows you're pitching: Reactivation + Missed-Call. Each
   missed-call item carries an `alt` = the AI-Voice-receptionist
   version, so the dashboard's Text-back ⇄ AI Voice toggle can
   swap them live in front of an owner.
   ============================================================ */

const DATASETS = {
  /* ---------------- HOSPITALITY — Trappe Tavern ---------------- */
  "trappe-tavern": {
    label: "Trappe Tavern", sub: "PAIS Control · 416 W Main St", theme: "tavern",
    eyebrow: "While you were closed",
    heroTitle: "7 regulars were slipping away. Every call got answered.",
    heroLine: "Overnight your agents pulled <b>7 regulars</b> worth winning back, caught a <b>missed call</b> (the AI can answer the next one live), and drafted your <b>review replies</b>. <b>5 drafts</b> waiting for your OK.",
    recovered: 4280, roiFoot: "+$960 this week",
    metrics: { reviews: 11, winbacks: 7, calls: 9, noshows: 4 },
    approvals: [
      { id: "t4", type: "reactivation", who: "Win back 7 quiet regulars", meta: "no visit in 40+ days",
        context: "<b>7 regulars</b> who used to come weekly haven't been in for 6 weeks. From the reservation log.",
        channel: "Send via email",
        draft: "Haven't seen you at the bar in a bit and it's not the same without you. Through Sunday: your next app is on the house — just show this. — The Trappe Tavern crew",
        value: 540 },
      { id: "t3", type: "missedcall", who: "Text back (610) 555-0148", meta: "missed at 9:52pm",
        context: "Call came in <b>after the host stand cleared</b>. Likely a reservation or large party.",
        channel: "Owner-send SMS",
        draft: "Hi! This is Trappe Tavern — sorry we missed you, the bar got loud 😄 Were you looking to book a table or ask about a party? Reply here and we'll get you set.",
        value: 180,
        alt: { who: "Confirm the table the AI booked", meta: "AI answered · 9:52pm",
          context: "<b>The AI receptionist picked up</b> and booked a party — the call was never missed. Just confirm.",
          channel: "Auto-added to your book — confirm",
          draft: "Dave · (610) 555-0148 · Fri 7:00pm · party of 6 · birthday", value: 180 } },
      { id: "t2", type: "reputation", who: "Ask 6 happy guests for a review", meta: "5★ visits · last night",
        context: "<b>6 guests</b> tipped 22%+ and stayed past close last night — prime 5★ candidates.",
        channel: "Send via email",
        draft: "Glad you closed the place down with us last night 🍻 If the wings + the Yuengling treated you right, a quick Google review helps the next neighbor find us: [review link]. — Trappe Tavern",
        value: 220 },
      { id: "t1", type: "reputation", who: "Reply to Dave M.", meta: "★★☆☆☆ · 2h ago",
        context: "Dave left a <b>2-star</b> review: “Waited 25 min for a table on Friday, no one checked on us.”",
        channel: "Post as Google reply",
        draft: "Hey Dave — that's on us, Friday got away from the floor and we should've kept you in the loop. We've added a host slot for weekend rushes. Come back in and let me buy your first round — see you at the bar. — Tom, Trappe Tavern",
        value: 0 },
      { id: "t5", type: "reputation", who: "Reply to Karen P.", meta: "★★★★★ · 5h ago",
        context: "Karen left a <b>5-star</b> review praising the new fall menu and the bartender Mike.",
        channel: "Post as Google reply",
        draft: "Karen, this made Mike's whole week 🙌 The fall menu was his pet project. Thanks for taking the time — see you next round. — Trappe Tavern",
        value: 0 },
    ],
    agents: [
      { key: "reactivation", ic: "↩", ac: "var(--brass)", name: "Reactivation", on: true, last: "Found 7 quiet regulars", stat: "7", lbl: "to win back" },
      { key: "missedcall", ic: "☎", ac: "var(--green)", name: "Missed-Call", on: true, last: "Caught 1 after-hours call",
        stat: "9", lbl: "saved / mo", voiceName: "AI Receptionist", voiceLast: "Answered 4 calls live · booked 2", voiceStat: "4", voiceLbl: "answered live" },
      { key: "reputation", ic: "★", ac: "var(--blue)", name: "Reputation", on: true, last: "Drafted 3 replies + 6 asks", stat: "4.3", lbl: "★ google" },
      { key: "digest", ic: "▤", ac: "var(--brass)", name: "Digest", on: true, last: "Compiled last night's room", stat: "11p", lbl: "peak" },
      { key: "reminders", ic: "⏰", ac: "var(--text-faint)", name: "Reminders", on: false, last: "Idle — needs a booking system", stat: "—", lbl: "off" },
    ],
    leaks: [
      { name: "Regulars drifting away", pct: 72, val: "7 re-engaged", note: "≈ $540" },
      { name: "After-hours calls → lost parties", pct: 64, val: "9 caught", note: "≈ $1,600" },
      { name: "Unanswered reviews → lost rank", pct: 82, val: "11 answered", note: "+1 star" },
      { name: "No-shows on weekend tables", pct: 30, val: "4 recovered", note: "≈ $300" },
    ],
    digest: { title: "Last night's room", sub: "Busiest hours & average tab",
      hours: [2,3,4,6,9,14,22,30,41,52,68,90,76,40], peakIdx: 11,
      stats: [{ num: "$34", lbl: "avg tab" }, { num: "11pm", lbl: "peak hour" }, { num: "Wings", lbl: "top seller" }] },
    feed: [
      { ic: "↩", ac: "var(--brass)", body: "<b>Reactivation</b> found 7 regulars quiet for 40+ days", time: "1h ago" },
      { ic: "☎", ac: "var(--green)", body: "<b>Missed-Call</b> caught a call at 9:52pm after the host left", time: "2h ago" },
      { ic: "★", ac: "var(--blue)", body: "<b>Reputation</b> drafted a reply to Dave M.'s 2★ review", time: "2h ago" },
      { ic: "▤", ac: "var(--brass)", body: "<b>Digest</b> flagged 11pm as last night's peak — staff the bar", time: "6h ago" },
    ],
    incoming: { id: "tlive", type: "missedcall", who: "Text back (484) 555-0193", meta: "missed just now",
      context: "<b>Live:</b> call came in and rang out — the floor's slammed right now.",
      channel: "Owner-send SMS",
      draft: "Hey! Trappe Tavern here — sorry we couldn't grab the phone, we're packed 🙌 Can we book you a table or answer a quick question? Just reply here.",
      value: 150, feedBody: "<b>Missed-Call</b> caught a live call — draft ready to send", toast: "☎ <b>New missed call</b> — text-back drafted",
      alt: { who: "Confirm the table the AI just booked", meta: "AI answered · just now",
        context: "<b>Live:</b> the AI receptionist answered the call and booked a table — never even rang out.",
        channel: "Auto-added to your book — confirm",
        draft: "New caller · (484) 555-0193 · Sat 8:00pm · party of 4", value: 150,
        feedBody: "<b>AI Receptionist</b> answered a live call and booked a table", toast: "🎙 <b>AI answered a live call</b> — table booked" } },
  },

  /* ---------------- FITNESS — TruFit ---------------- */
  "trufit": {
    label: "TruFit", sub: "PAIS Control · Phoenixville, PA", theme: "fitness",
    eyebrow: "Overnight report",
    heroTitle: "18 members were about to ghost. Every call got answered.",
    heroLine: "Your agents flagged <b>18 members</b> who stopped checking in, caught a <b>membership call</b> after hours (the AI can answer the next one live), and prepped tomorrow's <b>class reminders</b>. <b>5 drafts</b> waiting.",
    recovered: 6120, roiFoot: "+$1,540 this week",
    metrics: { reviews: 6, winbacks: 18, calls: 5, noshows: 11 },
    approvals: [
      { id: "f1", type: "reactivation", who: "Win back 18 fading members", meta: "no check-in in 14+ days",
        context: "<b>18 members</b> haven't scanned in for 2+ weeks — the window before they cancel. From Mindbody.",
        channel: "Send via email",
        draft: "We've missed you at TruFit 💪 Whatever knocked you off track, getting back is easier than you think — your spot's still here. Come in this week and your next month's small-group session is on us. — Mara",
        value: 3960 },
      { id: "f3", type: "missedcall", who: "Text back (484) 555-0211", meta: "missed at 8:14pm",
        context: "Call rang out after the front desk closed — almost certainly a <b>membership inquiry</b>.",
        channel: "Owner-send SMS",
        draft: "Hey! TruFit here — sorry we missed you after hours. Were you asking about membership or a class? Reply here and I'll get you a free week pass to try us out. — Mara",
        value: 90,
        alt: { who: "Confirm the tour the AI booked", meta: "AI answered · 8:14pm",
          context: "<b>The AI answered after hours</b> and booked a tour — the lead never bounced to another gym.",
          channel: "Auto-added to your calendar — confirm",
          draft: "Prospect · (484) 555-0211 · Sat 10am intro class · wants free week pass", value: 90 } },
      { id: "f4", type: "reactivation", who: "Re-engage 4 free-trial no-shows", meta: "signed up, never came",
        context: "<b>4 people</b> claimed a free trial this month and never walked in. Easiest win on the board.",
        channel: "Send via email",
        draft: "Your free trial at TruFit is still waiting! No pressure — even just a tour counts. Want me to hold a spot in this Saturday's intro class? — Mara",
        value: 880 },
      { id: "f2", type: "reminders", who: "Remind 14 booked into 6am Bootcamp", meta: "tomorrow · 6:00am",
        context: "<b>14 booked</b> for tomorrow's 6am bootcamp. A reminder tonight is the difference between a full floor and 6 people.",
        channel: "Owner-send SMS",
        draft: "See you at 6am bootcamp tomorrow 🔥 Reply C to confirm or X if you can't make it so someone on the waitlist can grab it. — TruFit",
        value: 0 },
      { id: "f5", type: "reputation", who: "Reply to Jordan K.", meta: "★★★★★ · 3h ago",
        context: "Jordan left a <b>5★</b> review crediting coach Sam for their first pull-up.",
        channel: "Post as Google reply",
        draft: "Jordan!! First pull-up is a HUGE milestone 🙌 Sam's going to be hyped. Thanks for being part of the TruFit family — onto the next goal. — Mara",
        value: 0 },
    ],
    agents: [
      { key: "reactivation", ic: "↩", ac: "var(--brass)", name: "Reactivation", on: true, last: "Flagged 18 fading members", stat: "18", lbl: "at-risk" },
      { key: "missedcall", ic: "☎", ac: "var(--green)", name: "Missed-Call", on: true, last: "Caught 1 membership call",
        stat: "5", lbl: "saved / mo", voiceName: "AI Receptionist", voiceLast: "Answered 3 calls live · booked 2 tours", voiceStat: "3", voiceLbl: "answered live" },
      { key: "reminders", ic: "⏰", ac: "var(--green)", name: "Class Reminders", on: true, last: "Prepped tomorrow's 6am bootcamp", stat: "11", lbl: "no-shows saved" },
      { key: "reputation", ic: "★", ac: "var(--blue)", name: "Reputation", on: true, last: "Drafted 1 reply + 2 asks", stat: "4.6", lbl: "★ google" },
      { key: "digest", ic: "▤", ac: "var(--brass)", name: "Digest", on: true, last: "6am & 6pm are your peaks", stat: "6a", lbl: "peak" },
    ],
    leaks: [
      { name: "Members churning silently", pct: 88, val: "18 re-engaged", note: "≈ $3,960" },
      { name: "After-hours membership calls", pct: 60, val: "5 caught", note: "new members" },
      { name: "Free trials that never show", pct: 55, val: "4 nudged", note: "≈ $880" },
      { name: "Class no-shows → dead floor", pct: 70, val: "11 confirmed", note: "fuller classes" },
    ],
    digest: { title: "Yesterday's floor", sub: "Check-ins by hour & class fill",
      hours: [44,30,18,12,16,28,40,33,22,30,55,72,50,20], peakIdx: 0,
      stats: [{ num: "182", lbl: "check-ins" }, { num: "6am", lbl: "peak hour" }, { num: "88%", lbl: "class fill" }] },
    feed: [
      { ic: "↩", ac: "var(--brass)", body: "<b>Reactivation</b> flagged 18 members with no check-in for 14+ days", time: "1h ago" },
      { ic: "☎", ac: "var(--green)", body: "<b>Missed-Call</b> caught a membership call at 8:14pm", time: "5h ago" },
      { ic: "⏰", ac: "var(--green)", body: "<b>Reminders</b> prepped 14 confirmations for tomorrow's 6am bootcamp", time: "3h ago" },
      { ic: "▤", ac: "var(--brass)", body: "<b>Digest</b> — 6am is your busiest hour, staff the desk early", time: "7h ago" },
    ],
    incoming: { id: "flive", type: "missedcall", who: "Text back (610) 555-0177", meta: "missed just now",
      context: "<b>Live:</b> someone called about joining and we couldn't pick up.",
      channel: "Owner-send SMS",
      draft: "Hey! TruFit here 💪 Sorry we missed your call — were you looking to join or book a tour? I can set you up with a free week pass. Just reply. — Mara",
      value: 110, feedBody: "<b>Missed-Call</b> caught a live join inquiry — draft ready", toast: "☎ <b>New membership call</b> — text-back drafted",
      alt: { who: "Confirm the tour the AI just booked", meta: "AI answered · just now",
        context: "<b>Live:</b> the AI answered the join inquiry and booked a tour — no lead lost.",
        channel: "Auto-added to your calendar — confirm",
        draft: "New prospect · (610) 555-0177 · Sun 11am tour · free week pass", value: 110,
        feedBody: "<b>AI Receptionist</b> answered a live join call and booked a tour", toast: "🎙 <b>AI answered a join call</b> — tour booked" } },
  },

  /* ---------------- PERSONAL CARE — Advanced Dentistry ---------------- */
  "advanced-dentistry": {
    label: "Advanced Dentistry", sub: "PAIS Control · Phoenixville, PA", theme: "clinic",
    eyebrow: "Before you opened",
    heroTitle: "23 overdue patients found. Every call answered.",
    heroLine: "Your agents surfaced <b>23 patients</b> overdue for a 6-month recall, caught a <b>new-patient call</b> at lunch (the AI can answer the next live), and confirmed <b>tomorrow's chairs</b>. <b>5 drafts</b> waiting for your OK.",
    recovered: 8740, roiFoot: "+$2,300 this week",
    metrics: { reviews: 5, winbacks: 23, calls: 6, noshows: 9 },
    approvals: [
      { id: "d3", type: "reactivation", who: "Recall 23 patients overdue for cleaning", meta: "no visit in 6+ months",
        context: "<b>23 patients</b> are past due for their 6-month hygiene visit — the single biggest revenue lever in the practice.",
        channel: "Send via email",
        draft: "It's been a while since your last cleaning, and your smile is due for some care 🦷 We've made booking easy — reply or call and we'll find a time that works. — The team at Advanced Dentistry",
        value: 4600 },
      { id: "d4", type: "missedcall", who: "Text back (610) 555-0162", meta: "missed at 12:40pm",
        context: "Call missed during the lunch block — likely a <b>new patient</b> trying to book.",
        channel: "Owner-send SMS",
        draft: "Hello! Sorry we missed your call to Advanced Dentistry — the team was with patients. Were you looking to book an appointment? Reply here and we'll get you scheduled. — The team",
        value: 120,
        alt: { who: "Confirm the appointment the AI booked", meta: "AI answered · 12:40pm",
          context: "<b>The AI answered during lunch</b> and booked a new patient — no front desk needed, no lost call.",
          channel: "Auto-added to your schedule — confirm",
          draft: "New patient · (610) 555-0162 · Thu 2:30pm · new-patient exam + cleaning", value: 120 } },
      { id: "d2", type: "reminders", who: "Nudge 2 unconfirmed appointments", meta: "no reply yet · high risk",
        context: "<b>2 patients</b> haven't confirmed tomorrow's slots — both are no-show risks worth ~$220 of chair time each.",
        channel: "Owner-send SMS",
        draft: "Just making sure we'll see you tomorrow! If the time doesn't work anymore, a quick reply lets us offer it to someone on our waitlist. — Advanced Dentistry",
        value: 440 },
      { id: "d1", type: "reminders", who: "Confirm 9 appointments for tomorrow", meta: "tomorrow's chairs",
        context: "<b>9 appointments</b> booked tomorrow. A confirm tonight is the difference between a full schedule and empty chairs.",
        channel: "Owner-send SMS",
        draft: "Hi! This is a reminder of your appointment tomorrow at Advanced Dentistry. Reply C to confirm or call us to reschedule. We look forward to seeing you! — The team",
        value: 0 },
      { id: "d5", type: "reputation", who: "Ask 4 patients for a review", meta: "smooth visits today",
        context: "<b>4 patients</b> had quick, on-time visits today — comfortable moments to ask for a review.",
        channel: "Send via email",
        draft: "Thanks for trusting us with your care today! If you have a moment, a short Google review helps other neighbors find a dentist they can relax with: [review link]. — Advanced Dentistry",
        value: 0 },
    ],
    agents: [
      { key: "reactivation", ic: "↩", ac: "var(--brass)", name: "Recall", on: true, last: "Found 23 overdue for cleaning", stat: "23", lbl: "to recall" },
      { key: "missedcall", ic: "☎", ac: "var(--green)", name: "Missed-Call", on: true, last: "Caught 1 lunchtime call",
        stat: "6", lbl: "saved / mo", voiceName: "AI Receptionist", voiceLast: "Answered 5 calls live · booked 3", voiceStat: "5", voiceLbl: "answered live" },
      { key: "reminders", ic: "⏰", ac: "var(--green)", name: "Reminders", on: true, last: "Confirmed tomorrow's 9 chairs", stat: "9", lbl: "no-shows saved" },
      { key: "reputation", ic: "★", ac: "var(--blue)", name: "Reputation", on: true, last: "Queued 4 review asks", stat: "4.8", lbl: "★ google" },
      { key: "digest", ic: "▤", ac: "var(--brass)", name: "Digest", on: true, last: "Chair utilization at 81%", stat: "2p", lbl: "peak" },
    ],
    leaks: [
      { name: "Overdue patients never recalled", pct: 92, val: "23 recalled", note: "≈ $4,600" },
      { name: "Missed new-patient calls", pct: 58, val: "6 caught", note: "new patients" },
      { name: "No-shows → empty chair time", pct: 64, val: "9 confirmed", note: "≈ $1,980" },
      { name: "Thin review count vs. rivals", pct: 38, val: "5 asks queued", note: "+rank" },
    ],
    digest: { title: "Yesterday's chairs", sub: "Bookings by hour & chair use",
      hours: [10,22,38,52,60,30,8,40,58,66,72,55,30,8], peakIdx: 10,
      stats: [{ num: "81%", lbl: "chair use" }, { num: "2pm", lbl: "peak hour" }, { num: "$214", lbl: "avg production" }] },
    feed: [
      { ic: "↩", ac: "var(--brass)", body: "<b>Recall</b> surfaced 23 patients overdue for a 6-month cleaning", time: "1h ago" },
      { ic: "☎", ac: "var(--green)", body: "<b>Missed-Call</b> caught a new-patient call at 12:40pm", time: "4h ago" },
      { ic: "⏰", ac: "var(--green)", body: "<b>Reminders</b> confirmed 9 of tomorrow's appointments", time: "2h ago" },
      { ic: "★", ac: "var(--blue)", body: "<b>Reputation</b> queued 4 review asks from today's smooth visits", time: "6h ago" },
    ],
    incoming: { id: "dlive", type: "missedcall", who: "Text back (484) 555-0150", meta: "missed just now",
      context: "<b>Live:</b> a call just rang out — the front desk is with a patient.",
      channel: "Owner-send SMS",
      draft: "Hello! Advanced Dentistry here — sorry we missed you, we were with a patient. Were you hoping to book an appointment? Reply and we'll get you scheduled. — The team",
      value: 120, feedBody: "<b>Missed-Call</b> caught a live new-patient call — draft ready", toast: "☎ <b>New patient call</b> — text-back drafted",
      alt: { who: "Confirm the appointment the AI just booked", meta: "AI answered · just now",
        context: "<b>Live:</b> the AI answered while the desk was with a patient and booked a new-patient exam.",
        channel: "Auto-added to your schedule — confirm",
        draft: "New patient · (484) 555-0150 · Fri 9:00am · new-patient exam", value: 120,
        feedBody: "<b>AI Receptionist</b> answered a live call and booked a new patient", toast: "🎙 <b>AI answered a live call</b> — patient booked" } },
  },
};
